### ISSUE TITLE
Some output files are empty (0 bytes)

### ISSUE THREAD

**Issue by ultra2** [rndD/package-cleanup#4]
Some output files are empty (0 bytes)!!!

I used the recommended patterns:

```
**/*.js
**/*.css
img/*.{jpg,png,svg}
```

**Comment by anton-rudeshko** [comment]
It's intended to be empty? You can use `--delete-empty` option.

**Comment by rndD** [comment]
Hi, thank you for feedback. Can you show me what `tree` commad is showing before and after cleanup? What version of **package-cleanup** are you using?
